config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :messages
  resources :chatrooms do
  	resources :memberships, only: [:create]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#home'

  get 'home/get_chatrooms', defaults: { format: 'json' }
  get 'home/get_users', defaults: { format: 'json' }

  mount ActionCable.server => '/cable'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action :authenticate_user!
  
  def home
    @chatroom = Chatroom.where(name: "general").first
    @messages = @chatroom.messages
    @message = Message.new
  	if user_signed_in?

  	else
  		redirect_to new_user_session_path
  	end
  end

  def get_chatrooms
    @chatrooms = Chatroom.all
    respond_to do |format|
      format.json {render json: @chatrooms}
    end
  end

  def get_users
    @users = User.all

    respond_to do |format|
      format.json {render json: @users}
    end

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<%= render partial: 'partials/navbar' %>
<div class="container-fluid" ng-app="home">
	<div class="row" ng-controller="homeCtrl">
		<div class="col-sm-3 col-md-2 hidden-xs-down sidebar">
			<h4 class="text-info text-center">Channels</h4>
			<ul class="list-group" ng-repeat="chatroom in data.chatrooms">
				<li class= "badge"  ng-if="chatroom.name != 'general' ">
					<h6>
						<%= link_to '{{chatroom.name}}', URI::decode_www_form_component(  chatroom_path('{{chatroom.id}}')), class: "nav-link text-warning" %>
					</h6>
				</li>
			</ul>
		</div>
		<div class="col-md-8" id="general-chat">
			<div class="bg-warning text-center">
				<h4><%= @chatroom.name %></h4>
			</div>
			<div id="messages-table" class="bg-faded" data-chat-room-id="<%= @chatroom.id %>">
				<%= render partial: 'messages/message', collection: @messages %>
			</div>
			<div class="form-group">
				<%= render partial: 'messages/message_form', locals: {message: @message , chatroom: @chatroom} %>
			</div>
		</div>
	</div>
</div>